import { jsx as _jsx, jsxs as _jsxs } from "hono/jsx/jsx-runtime";
import Button from "./components/button";
import { customFood, submitCustomFoodForm, updateFormFields } from "./customFoodForm";
function createNutrition() {
    function handleSubmit(event) {
        event.preventDefault();
        submitCustomFoodForm();
    }
    return (_jsx("div", { class: "w-full max--xs flex items-center justify-center", children: _jsxs("form", { onClick: handleSubmit, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", children: [_jsx("label", { class: "block text-gray-700 text-sm font-black", children: "Food Name" }), _jsx("input", { value: customFood.foodName, onChange: updateFormFields('foodName'), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700" }), _jsx("label", { class: "block text-gray-700 text-sm font-bold mb-2", children: "Default Calories" }), _jsx("input", { value: customFood.defaultCalories, onchange: updateFormFields('defaultCalories'), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700" }), _jsx("label", { class: "block text-gray-700 text-sm font-bold mb-2", children: "Default Protein" }), _jsx("input", { value: customFood.defaultProtein, onChange: updateFormFields('defaultProtein'), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700" }), _jsx("label", { class: "block text-gray-700 text-sm font-bold mb-2", children: "Default Carbs" }), _jsx("input", { value: customFood.defaultCarbs, onChange: updateFormFields('defaultCarbs'), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700" }), _jsx("label", { class: "block text-gray-700 text-sm font-bold mb-2", children: "Default Serving" }), _jsx("input", { value: customFood.defaultServing, onChange: updateFormFields('defaultServing'), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700" }), _jsx("label", { class: "block text-gray-700 text-sm font-bold mb-2", children: "Default Fat" }), _jsx("input", { value: customFood.defaultFat, onChange: updateFormFields('defaultFat'), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700" }), _jsx("div", { class: "flex items-center justify-center", children: _jsx(Button, { children: "Submit" }) })] }) }));
}
export default createNutrition;
